[[main]]
  name = "Posts"
  url = "post"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 50

[[main]]
  name = "Leetcode"
  url = "leetcode"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70