language: node_js
sudo: required
node_js: stable

cache:
  directories:
    -node_modules

branches:
  only:
    - hexo  #只对Hexo分支进行构建

# S: Build Lifecycle
before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./publicx
  - git init
  - git config --global user.name "guozetang"
  - git config --global user.email "guozetang@gmail.com"
  - git commit -m "Travis CI Auto Builder."
  - git push --quiet --force https://$REPO_TOKEN@github.com/guozetang/guozetang.github.io.git master
# E: Build LifeCycle



