language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./publicx
  - git init
  - git config user.name "guozetang"
  - git config user.email "guozetang@gmail.com"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo  #只对Hexo分支进行构建

env:
 global:
   - GH_REF: github.com/guozetang/$guozetang.github.io
